<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitDeck.Core\GitDeck.Core.csproj" />
    <ProjectReference Include="..\GitDeck.Git\GitDeck.Git.csproj" />
    <ProjectReference Include="..\GitDeck.App\GitDeck.App.csproj" />
    <ProjectReference Include="..\GitDeck.Ipc\GitDeck.Ipc.csproj" />
  </ItemGroup>

</Project>
