<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GitDeck.Core\GitDeck.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GitDeck.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.39.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
  </ItemGroup>

</Project>
